use std::future::Future;

use crate::domain::{
    error::DomainError,
    rank::{entities::Rank, ports::RankService},
};

use super::{
    entities::{
        field::{Field, FieldConfig},
        flow::Flow,
        ids::{FieldId, FlowId, StepId},
        step::Step,
    },
    ports::{
        FieldRepository, FieldService, FlowRepository, FlowService, StepRepository, StepService,
    },
};

/// A concrete implementation that provides the application-level services for
/// flows, steps and fields.
///
/// The `FlowServiceImpl` acts as an orchestrator: it implements the `FlowService`,
/// `StepService` and `FieldService` traits and delegates persistence to the
/// provided repository implementations. It also uses a `RankService` to compute
/// ordering ranks for steps and fields.
///
/// Type parameters:
/// - `FR`: type implementing `FlowRepository` (storage for flows)
/// - `SR`: type implementing `StepRepository` (storage for steps)
/// - `FDR`: type implementing `FieldRepository` (storage for fields)
/// - `RS`: type implementing `RankService` (rank generation)
///
/// Example:
/// ```no_run
/// # use ferrisquote::domain::flows::ports::*;
/// # use ferrisquote::domain::rank::ports::RankService;
/// # struct MyFlowRepo; struct MyStepRepo; struct MyFieldRepo; struct MyRankSvc;
/// # impl FlowRepository for MyFlowRepo { /* ... */ }
/// # impl StepRepository for MyStepRepo { /* ... */ }
/// # impl FieldRepository for MyFieldRepo { /* ... */ }
/// # impl RankService for MyRankSvc { /* ... */ }
/// let svc = FlowServiceImpl::new(MyFlowRepo, MyStepRepo, MyFieldRepo, MyRankSvc);
/// ```
#[derive(Clone)]
pub struct FlowServiceImpl<FR, SR, FDR, RS> {
    flow_repo: FR,
    step_repo: SR,
    field_repo: FDR,
    rank_service: RS,
}

impl<FR, SR, FDR, RS> FlowServiceImpl<FR, SR, FDR, RS> {
    /// Construct a new `FlowServiceImpl`.
    ///
    /// Parameters:
    /// - `flow_repo`: repository handling `Flow` persistence.
    /// - `step_repo`: repository handling `Step` persistence.
    /// - `field_repo`: repository handling `Field` persistence.
    /// - `rank_service`: service used to compute lexicographic ranks.
    ///
    /// The returned value implements `FlowService`, `StepService` and `FieldService`
    /// as long as the repository/service types implement the corresponding traits.
    pub fn new(flow_repo: FR, step_repo: SR, field_repo: FDR, rank_service: RS) -> Self {
        Self {
            flow_repo,
            step_repo,
            field_repo,
            rank_service,
        }
    }
}

impl<FR, SR, FDR, RS> FlowService for FlowServiceImpl<FR, SR, FDR, RS>
where
    FR: FlowRepository + Send + Sync,
    SR: StepRepository + Send + Sync,
    FDR: FieldRepository + Send + Sync,
    RS: RankService + Send + Sync,
{
    // --- Flow management ---

    /// Create a new flow with the given `name`.
    ///
    /// This will instantiate a domain `Flow` with an autogenerated id and empty
    /// steps list, then delegate persistence to the configured `FlowRepository`.
    ///
    /// Returns a future that resolves to the created `Flow` or a `DomainError`.
    fn create_flow(&self, name: String) -> impl Future<Output = Result<Flow, DomainError>> + Send {
        let repo = &self.flow_repo;
        async move {
            let flow = Flow::new(name, String::new());
            repo.create_flow(flow).await
        }
    }

    /// Fetch a flow by id.
    ///
    /// Delegates to `FlowRepository::get_flow`.
    fn get_flow(&self, id: FlowId) -> impl Future<Output = Result<Flow, DomainError>> + Send {
        let repo = &self.flow_repo;
        async move { repo.get_flow(id).await }
    }

    /// List all flows.
    ///
    /// Delegates to `FlowRepository::list_flows`.
    fn list_flows(&self) -> impl Future<Output = Result<Vec<Flow>, DomainError>> + Send {
        let repo = &self.flow_repo;
        async move { repo.list_flows().await }
    }

    /// Update flow metadata (name and optional description).
    ///
    /// Loads the flow, mutates its metadata and persists the updated flow.
    /// Produces a `DomainError` if the flow cannot be retrieved or updated.
    fn update_flow_metadata(
        &self,
        id: FlowId,
        name: Option<String>,
        description: Option<String>,
    ) -> impl Future<Output = Result<Flow, DomainError>> + Send {
        let repo = &self.flow_repo;
        async move {
            // Use the repository partial-update API to update only the provided fields.
            // This avoids an extra select-and-rewrite on the caller side.
            repo.update_flow(id, name, description).await
        }
    }

    /// Delete a flow by id.
    ///
    /// Delegates to `FlowRepository::delete_flow`.
    fn delete_flow(&self, id: FlowId) -> impl Future<Output = Result<(), DomainError>> + Send {
        let repo = &self.flow_repo;
        async move { repo.delete_flow(id).await }
    }
}

impl<FR, SR, FDR, RS> StepService for FlowServiceImpl<FR, SR, FDR, RS>
where
    FR: FlowRepository + Send + Sync,
    SR: StepRepository + Send + Sync,
    FDR: FieldRepository + Send + Sync,
    RS: RankService + Send + Sync,
{
    // --- Step management ---

    /// Add a new step to a flow.
    ///
    /// The service:
    /// 1. Fetches the target flow to determine the last step's rank (if any).
    /// 2. Uses the `RankService` to compute the next rank (or initial rank if empty).
    /// 3. Constructs a domain `Step` and delegates persistence to `StepRepository::create_step`.
    ///
    /// Returns the created `Step` or a `DomainError`.
    fn add_step(
        &self,
        flow_id: FlowId,
        title: String,
    ) -> impl Future<Output = Result<Step, DomainError>> + Send {
        let flow_repo = &self.flow_repo;
        let step_repo = &self.step_repo;
        let rank_svc = &self.rank_service;

        async move {
            let flow = flow_repo.get_flow(flow_id).await?;

            let next_rank = match flow.steps.get(flow.steps.len().saturating_sub(1)) {
                Some(last_step) => rank_svc.after(&Rank::from_string(last_step.rank.clone())),
                None => rank_svc.initial(),
            };

            // Note: `Step::new` expects the `rank` as a `String`.
            let step = Step::new(title, String::new(), next_rank.as_str().to_string());

            step_repo.create_step(flow_id, step).await
        }
    }

    /// Remove a step by id.
    ///
    /// Delegates to `StepRepository::delete_step`.
    fn remove_step(&self, step_id: StepId) -> impl Future<Output = Result<(), DomainError>> + Send {
        let step_repo = &self.step_repo;
        async move { step_repo.delete_step(step_id).await }
    }

    /// Reorder a step within its flow.
    ///
    /// This operation is currently unimplemented here because it requires
    /// additional repository capabilities (for example: `get_step` that returns
    /// the owning flow id, or a repository function to atomically update multiple steps).
    ///
    /// Returns a `DomainError::internal` until implemented.
    fn reorder_step(
        &self,
        step_id: StepId,
        after_id: Option<StepId>,
        before_id: Option<StepId>,
    ) -> impl Future<Output = Result<Flow, DomainError>> + Send {
        // Implementation:
        // 1. Resolve rank of surrounding steps (if any) via StepRepository::get_step
        // 2. Compute new rank using RankService
        // 3. Persist rank using StepRepository::update_step (partial update)
        // 4. Return the Flow containing the step by scanning flows (FlowRepository::list_flows)
        let flow_repo = &self.flow_repo;
        let step_repo = &self.step_repo;
        let rank_svc = &self.rank_service;

        async move {
            // Resolve neighbor ranks
            let after_rank = if let Some(id) = after_id {
                Some(step_repo.get_step(id).await?.rank)
            } else {
                None
            };
            let before_rank = if let Some(id) = before_id {
                Some(step_repo.get_step(id).await?.rank)
            } else {
                None
            };

            // Compute new rank keeping the same algorithm as before
            let new_rank = match (after_rank, before_rank) {
                (Some(a), Some(b)) => {
                    let a_r = Rank::from_string(a);
                    let b_r = Rank::from_string(b);
                    rank_svc.between(&a_r, &b_r)
                }
                (Some(a), None) => {
                    let a_r = Rank::from_string(a);
                    rank_svc.after(&a_r)
                }
                (None, Some(b)) => {
                    let b_r = Rank::from_string(b);
                    rank_svc.before(&b_r)
                }
                (None, None) => rank_svc.initial(),
            };

            // Persist the new rank on the step (partial update)
            step_repo
                .update_step(step_id, None, None, Some(new_rank.as_str().to_string()))
                .await?;

            // Find and return the flow that contains this step
            let flows = flow_repo.list_flows().await?;
            let found = flows
                .into_iter()
                .find(|f| f.get_step(&step_id).is_some())
                .ok_or_else(|| {
                    DomainError::not_found("Flow containing step", format!("{:?}", step_id))
                })?;

            Ok(found)
        }
    }

    fn update_step_metadata(
        &self,
        step_id: StepId,
        title: Option<String>,
        description: Option<String>,
    ) -> impl Future<Output = Result<Step, DomainError>> + Send {
        self.step_repo
            .update_step(step_id, title, description, None)
    }
}

impl<FR, SR, FDR, RS> FieldService for FlowServiceImpl<FR, SR, FDR, RS>
where
    FR: FlowRepository + Send + Sync,
    SR: StepRepository + Send + Sync,
    FDR: FieldRepository + Send + Sync,
    RS: RankService + Send + Sync,
{
    // --- Field management (Field Builder) ---

    /// Add a new field to a step.
    ///
    /// Steps:
    /// 1. Fetch the step via `StepRepository::get_step` to compute the last field rank.
    /// 2. Use the `RankService` to compute the next rank (or initial rank if empty).
    /// 3. Build the domain `Field` and persist via `FieldRepository::create_field`.
    ///
    /// Returns the created `Field` or a `DomainError`.
    fn add_field(
        &self,
        step_id: StepId,
        label: String,
        key: String,
        config: FieldConfig,
    ) -> impl Future<Output = Result<Field, DomainError>> + Send {
        let step_repo = &self.step_repo;
        let field_repo = &self.field_repo;
        let rank_svc = &self.rank_service;

        async move {
            // Fetch the step to compute the next rank for the new field
            let step = step_repo.get_step(step_id).await?;

            let next_rank = match step.fields.get(step.fields.len().saturating_sub(1)) {
                Some(last_field) => rank_svc.after(&Rank::from_string(last_field.rank.clone())),
                None => rank_svc.initial(),
            };

            // Field::new(key, label, description, rank, config)
            let field = Field::new(
                key,
                label,
                String::new(),
                next_rank.as_str().to_string(),
                config,
            );

            field_repo.create_field(step_id, field).await
        }
    }

    /// Update a field's configuration (label + config).
    ///
    /// Currently unimplemented: updating requires reading the existing field,
    /// mutating it and persisting it. That requires an additional repository
    /// method (e.g. `get_field`) which is not present in the minimal ports.
    fn update_field_config(
        &self,
        field_id: FieldId,
        label: Option<String>,
        config: Option<FieldConfig>,
    ) -> impl Future<Output = Result<Field, DomainError>> + Send {
        // Use the repository partial-update API for fields. Only provided fields
        // (Some(..)) will be updated by the repository.
        let field_repo = &self.field_repo;
        async move {
            // key and description are not provided here, pass None for them;
            // repository will update only the provided fields.
            field_repo
                .update_field(field_id, None, label, None, config)
                .await
        }
    }

    /// Remove a field by id.
    ///
    /// Delegates to `FieldRepository::delete_field`.
    fn remove_field(
        &self,
        field_id: FieldId,
    ) -> impl Future<Output = Result<(), DomainError>> + Send {
        let field_repo = &self.field_repo;
        async move { field_repo.delete_field(field_id).await }
    }

    /// Move a field to another step or change its order.
    ///
    /// This complex operation requires fetching and updating multiple entities
    /// atomically; it's left unimplemented here and will return an internal
    /// error until repository support for multi-entity updates exists.
    fn move_field(
        &self,
        field_id: FieldId,
        target_step_id: Option<StepId>,
        after_id: Option<FieldId>,
        before_id: Option<FieldId>,
    ) -> impl Future<Output = Result<Flow, DomainError>> + Send {
        let flow_repo = &self.flow_repo;
        let field_repo = &self.field_repo;
        let step_repo = &self.step_repo;
        let rank_svc = &self.rank_service;

        async move {
            let flows = flow_repo.list_flows().await?;
            let mut found: Option<(Flow, StepId, Field)> = None;
            for f in flows.into_iter() {
                for s in f.steps.iter() {
                    if let Some(field) = s.get_field(&field_id) {
                        found = Some((f.clone(), s.id, field.clone()));
                        break;
                    }
                }
                if found.is_some() {
                    break;
                }
            }

            let (flow, source_step_id, field) =
                found.ok_or_else(|| DomainError::not_found("Field", format!("{:?}", field_id)))?;

            // Determine the target step
            let target_step = target_step_id.unwrap_or(source_step_id);

            // Helper to find rank of neighbor field ids (searching within the flow)
            let find_field_rank = |fid: FieldId| -> Option<String> {
                for s in flow.steps.iter() {
                    if let Some(fld) = s.get_field(&fid) {
                        return Some(fld.rank.clone());
                    }
                }
                None
            };

            let after_rank = if let Some(aid) = after_id {
                find_field_rank(aid)
            } else {
                None
            };
            let before_rank = if let Some(bid) = before_id {
                find_field_rank(bid)
            } else {
                None
            };

            // Compute new rank using the same algorithm as for steps
            let new_rank = match (after_rank, before_rank) {
                (Some(a), Some(b)) => {
                    let a_r = Rank::from_string(a);
                    let b_r = Rank::from_string(b);
                    rank_svc.between(&a_r, &b_r)
                }
                (Some(a), None) => {
                    let a_r = Rank::from_string(a);
                    rank_svc.after(&a_r)
                }
                (None, Some(b)) => {
                    let b_r = Rank::from_string(b);
                    rank_svc.before(&b_r)
                }
                (None, None) => {
                    // If target step has existing fields, put after last; else initial
                    if let Ok(ts) = step_repo.get_step(target_step).await {
                        if let Some(last) = ts.fields.get(ts.fields.len().saturating_sub(1)) {
                            rank_svc.after(&Rank::from_string(last.rank.clone()))
                        } else {
                            rank_svc.initial()
                        }
                    } else {
                        rank_svc.initial()
                    }
                }
            };

            // Remove original and create a new field with same id under target step.
            // Using delete+create keeps the service implementation agnostic to whether
            // repositories support partial rank updates on fields.
            field_repo.delete_field(field_id).await?;

            let new_field = Field::with_id(
                field.id,
                field.key,
                field.label,
                field.description,
                new_rank.as_str().to_string(),
                field.config,
            );

            field_repo.create_field(target_step, new_field).await?;

            // Return refreshed flow
            flow_repo.get_flow(flow.id).await
        }
    }

    /// Search for fields within a flow.
    ///
    /// Delegates to the repository `get_flow_fields`.
    fn search_flow_fields(
        &self,
        flow_id: FlowId,
        query: Option<String>,
    ) -> impl Future<Output = Result<Vec<Field>, DomainError>> + Send {
        let field_repo = &self.field_repo;
        async move { field_repo.get_flow_fields(flow_id, query).await }
    }
}
