ALTER TABLE steps
  ADD COLUMN is_repeatable BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN repeat_label VARCHAR(255),
  ADD COLUMN min_repeats INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN max_repeats INTEGER;
