CREATE TABLE fields (
  id UUID PRIMARY KEY,
  steps_id UUID NOT NULL,
  "key" VARCHAR(32) NOT NULL,
  label VARCHAR(255) NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  config JSONB NOT NULL,
  rank VARCHAR(255) NOT NULL DEFAULT 'n',

  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_fields_steps_id FOREIGN KEY (steps_id) REFERENCES steps(id) ON DELETE CASCADE
);

CREATE INDEX idx_fields_steps_rank ON fields (steps_id, rank);
