use utoipa::OpenApi;

use crate::dto::{
    ApiResponse, CreateEstimatorRequest, CreateFieldRequest, CreateFlowRequest,
    CreateStepRequest, CreateVariableRequest, EstimatorListResponse, EstimatorResponse,
    EvaluateFlowResponse, EvaluateRequest, EvaluateResponse, EvaluateSubmissionRequest,
    FieldConfigDto, FieldResponse, FlowListResponse, FlowResponse, FlowSummaryResponse,
    MessageResponse, MoveFieldRequest, ReorderStepRequest, StepResponse, UpdateEstimatorRequest,
    UpdateFieldConfigRequest, UpdateFlowMetadataRequest, UpdateStepMetadataRequest,
    UpdateVariableRequest, VariableResponse,
};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "FerrisQuote API",
        version = "0.1.0",
        description = "API for managing quote flows, steps, fields and estimators"
    ),
    paths(
        crate::handlers::flow_handlers::create_flow,
        crate::handlers::flow_handlers::list_flows,
        crate::handlers::flow_handlers::get_flow,
        crate::handlers::flow_handlers::update_flow_metadata,
        crate::handlers::flow_handlers::delete_flow,
        crate::handlers::step_handlers::add_step,
        crate::handlers::step_handlers::remove_step,
        crate::handlers::step_handlers::reorder_step,
        crate::handlers::step_handlers::update_step_metadata,
        crate::handlers::field_handlers::add_field,
        crate::handlers::field_handlers::update_field_config,
        crate::handlers::field_handlers::remove_field,
        crate::handlers::field_handlers::move_field,
        crate::handlers::estimator_handlers::create_estimator,
        crate::handlers::estimator_handlers::list_estimators,
        crate::handlers::estimator_handlers::get_estimator,
        crate::handlers::estimator_handlers::update_estimator,
        crate::handlers::estimator_handlers::delete_estimator,
        crate::handlers::estimator_handlers::add_variable,
        crate::handlers::estimator_handlers::update_variable,
        crate::handlers::estimator_handlers::remove_variable,
        crate::handlers::estimator_handlers::evaluate,
        crate::handlers::estimator_handlers::evaluate_submission,
        crate::handlers::estimator_handlers::evaluate_flow,
    ),
    components(schemas(
        CreateFlowRequest,
        UpdateFlowMetadataRequest,
        FlowResponse,
        FlowListResponse,
        FlowSummaryResponse,
        CreateStepRequest,
        UpdateStepMetadataRequest,
        ReorderStepRequest,
        StepResponse,
        CreateFieldRequest,
        UpdateFieldConfigRequest,
        MoveFieldRequest,
        FieldResponse,
        FieldConfigDto,
        CreateEstimatorRequest,
        UpdateEstimatorRequest,
        EstimatorResponse,
        EstimatorListResponse,
        CreateVariableRequest,
        UpdateVariableRequest,
        VariableResponse,
        EvaluateRequest,
        EvaluateSubmissionRequest,
        EvaluateResponse,
        EvaluateFlowResponse,
        MessageResponse,
        ApiResponse<FlowResponse>,
        ApiResponse<FlowListResponse>,
        ApiResponse<StepResponse>,
        ApiResponse<FieldResponse>,
        ApiResponse<EstimatorResponse>,
        ApiResponse<EstimatorListResponse>,
        ApiResponse<VariableResponse>,
        ApiResponse<EvaluateResponse>,
        ApiResponse<EvaluateFlowResponse>,
        ApiResponse<MessageResponse>,
    )),
    tags(
        (name = "flows", description = "Flow management"),
        (name = "steps", description = "Step management"),
        (name = "fields", description = "Field management"),
        (name = "estimators", description = "Estimator management"),
        (name = "estimator_variables", description = "Estimator variable management"),
    )
)]
pub struct ApiDoc;
