use utoipa::OpenApi;

use crate::dto::{
    AggregationStrategyDto, ApiResponse, BindingListResponse, BindingResponse,
    CreateBindingRequest, CreateEstimatorRequest, CreateFieldRequest, CreateFlowRequest,
    CreateInputRequest, CreateOutputRequest, CreateStepRequest, EstimatorListResponse,
    EstimatorParameterTypeDto, EstimatorResponse, EvaluateBindingsRequest, EvaluateFlowResponse,
    EvaluateRequest, EvaluateResponse, EvaluateSubmissionRequest, FieldConfigDto, FieldResponse,
    FieldValueDto, FlowEvaluationResponse, FlowListResponse, FlowPreviewResponse, FlowResponse,
    FlowSummaryResponse, InputBindingValueDto, InputResponse, MessageResponse, MoveFieldRequest,
    OutputResponse, ReorderStepRequest, StepIterationDto, StepResponse, SubmissionListResponse,
    SubmissionResponse, SubmitAnswersRequest, UpdateBindingRequest, UpdateEstimatorRequest,
    UpdateFieldConfigRequest, UpdateFlowMetadataRequest, UpdateInputRequest, UpdateOutputRequest,
    UpdateStepMetadataRequest,
};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "FerrisQuote API",
        version = "0.1.0",
        description = "API for managing quote flows, steps, fields and estimators"
    ),
    paths(
        crate::handlers::flow_handlers::create_flow,
        crate::handlers::flow_handlers::list_flows,
        crate::handlers::flow_handlers::get_flow,
        crate::handlers::flow_handlers::update_flow_metadata,
        crate::handlers::flow_handlers::delete_flow,
        crate::handlers::step_handlers::add_step,
        crate::handlers::step_handlers::remove_step,
        crate::handlers::step_handlers::reorder_step,
        crate::handlers::step_handlers::update_step_metadata,
        crate::handlers::field_handlers::add_field,
        crate::handlers::field_handlers::update_field_config,
        crate::handlers::field_handlers::remove_field,
        crate::handlers::field_handlers::move_field,
        crate::handlers::estimator_handlers::create_estimator,
        crate::handlers::estimator_handlers::list_estimators,
        crate::handlers::estimator_handlers::get_estimator,
        crate::handlers::estimator_handlers::update_estimator,
        crate::handlers::estimator_handlers::delete_estimator,
        crate::handlers::estimator_handlers::add_input,
        crate::handlers::estimator_handlers::update_input,
        crate::handlers::estimator_handlers::remove_input,
        crate::handlers::estimator_handlers::add_output,
        crate::handlers::estimator_handlers::update_output,
        crate::handlers::estimator_handlers::remove_output,
        crate::handlers::estimator_handlers::evaluate,
        crate::handlers::estimator_handlers::evaluate_submission,
        crate::handlers::estimator_handlers::evaluate_flow,
        crate::handlers::submission_handlers::submit_answers,
        crate::handlers::submission_handlers::get_submission_by_id,
        crate::handlers::submission_handlers::list_submissions_for_flow,
        crate::handlers::binding_handlers::add_binding,
        crate::handlers::binding_handlers::list_bindings,
        crate::handlers::binding_handlers::update_binding,
        crate::handlers::binding_handlers::remove_binding,
        crate::handlers::evaluation_handlers::evaluate_bindings,
        crate::handlers::evaluation_handlers::preview_flow,
    ),
    components(schemas(
        CreateFlowRequest,
        UpdateFlowMetadataRequest,
        FlowResponse,
        FlowListResponse,
        FlowSummaryResponse,
        CreateStepRequest,
        UpdateStepMetadataRequest,
        ReorderStepRequest,
        StepResponse,
        CreateFieldRequest,
        UpdateFieldConfigRequest,
        MoveFieldRequest,
        FieldResponse,
        FieldConfigDto,
        CreateEstimatorRequest,
        UpdateEstimatorRequest,
        EstimatorResponse,
        EstimatorListResponse,
        EstimatorParameterTypeDto,
        CreateInputRequest,
        UpdateInputRequest,
        InputResponse,
        CreateOutputRequest,
        UpdateOutputRequest,
        OutputResponse,
        EvaluateRequest,
        EvaluateSubmissionRequest,
        EvaluateResponse,
        EvaluateFlowResponse,
        MessageResponse,
        FieldValueDto,
        StepIterationDto,
        SubmitAnswersRequest,
        SubmissionResponse,
        SubmissionListResponse,
        AggregationStrategyDto,
        InputBindingValueDto,
        CreateBindingRequest,
        UpdateBindingRequest,
        BindingResponse,
        BindingListResponse,
        EvaluateBindingsRequest,
        FlowEvaluationResponse,
        FlowPreviewResponse,
        ApiResponse<FlowResponse>,
        ApiResponse<FlowListResponse>,
        ApiResponse<StepResponse>,
        ApiResponse<FieldResponse>,
        ApiResponse<EstimatorResponse>,
        ApiResponse<EstimatorListResponse>,
        ApiResponse<InputResponse>,
        ApiResponse<OutputResponse>,
        ApiResponse<EvaluateResponse>,
        ApiResponse<EvaluateFlowResponse>,
        ApiResponse<MessageResponse>,
        ApiResponse<SubmissionResponse>,
        ApiResponse<SubmissionListResponse>,
        ApiResponse<BindingResponse>,
        ApiResponse<BindingListResponse>,
    )),
    tags(
        (name = "flows", description = "Flow management"),
        (name = "steps", description = "Step management"),
        (name = "fields", description = "Field management"),
        (name = "estimators", description = "Estimator management"),
        (name = "estimator_signature", description = "Estimator inputs & outputs"),
        (name = "submissions", description = "Flow answer submissions"),
        (name = "bindings", description = "Estimator bindings (Map/Reduce pipeline)"),
        (name = "evaluation", description = "DAG-based flow evaluation"),
    )
)]
pub struct ApiDoc;
